### ISSUE TITLE
Add owner protection period in cancelOffer function

### ISSUE THREAD

**Issue by hashkitty** [dapperlabs/cryptokitties-bounty-2#47]
### Description
Player can submit an offer and cancel it before customer has time to react. Since offer acceptance involves at least 2 transaction versus 1 in offer cancellation, bidder always has time advantage. Though bidder pays offer cut, it might not be enough to stop attacks in some cases.

### Scenario
- Bidder creates an offer
- Owner wants to accept offer and sends approve transaction for Kitty Core project
- Bidder cancels offer which leaves owner's token in potentially vulnerable situation when token is already approved for Offers contract but no offer exists.

### Impact
Bidder can block offers of other players or downgrade his own offer.

### Fix
Implemented configurable owner protection period in Offers contract. For example add following statement in cancelOffer function:
```
require(offer.created + ownerProtectionPeriod < now, "cannot cancel offer before customer protection expires")
```

**Comment by ghost** [comment]
Owners are already protected against your attack since the owner only calls `.approve()` along with sending a `_minOfferPrice` to CK off-chain. Issue #22 addresses why sending `_minOfferPrice` off-chain is dangerous, so CK will address that. Once CK addresses that, the `_minOfferPrice` variable will address your concern.

Additionally, your suggestion seems rather dangerous, since it forces a bidder to not be able to cancel on-chain for a certain period of time, even if they want to.

For example:
Imagine that a bidder accidentally bids too much on a cat. They immediately recognize their mistake and try to call `.cancelOffer()`. However, if your suggestion were implemented, they would be forced to keep that offer. The owner would take advantage of the situation and accept the outrageous offer, taking advantage of the bidder.

One of the goals of CK's ReadMe is to prioritize the UX for the user - that includes the Bidder. If Bidders are unable to cancel their bids, that would be a very frustrating (and potentially costly) user experience.

**Comment by hwrdtm** [comment]
Thanks @hashkitty for your feedback.

We are aware of the scenario you mentioned and believe that having a cancellation fee set at an appropriate value is a good enough disincentive.

Closing for now.
