### ISSUE TITLE
Users may pay higher fees than expected during bidding

### ISSUE THREAD

**Issue by pengocat** [dapperlabs/cryptokitties-bounty-2#50]
### Description
There is a fee expectation when a user creates a bid for a token. This could be violated if the parameters of the fee calculation are changed by the COO after the bid is created, but before it is accepted or rejected. 

The function offerCut is called inside function fulfillOffer instead of function createOffer. This means the fees are calculated at the time of offer fulfillment instead of offer creation. However, the COO has the power to change the fees per function _setOfferCut. If this change happens after createOffer is called but before fulfillOffer is called, the user could unexpectedly pay a high fees. 

### Scenario
User creates an offer for 1 ETH, and expects to pay a fee of 0.001 ETH based on current fee structure. The offer remains open. The COO changes fees. The user might end up paying 0.002 ETH fees based on updated fee structure.  

### Impact
Medium.

### Fix
The calculation of fees should happen at the time of offer creation instead of offer acceptance to avoid this scenario. The fees should then be stored along with the offer, and that value should be used instead of re-calculating the fees. Of course, there is a trade-off of storage in this case. Not a clean fix.

**Comment by ghost** [comment]
This is not true. 

`.fulfillOffer()` uses the `offerCut` that was saved in the `Offer` struct at the time that that particular offer was created. Your post suggests that `.fulfillOffer()` uses the global value of `offerCut`, but it does not.

Additionally, you suggest that:
>The calculation of fees should happen at the time of offer creation

However, this would consume unnecessary gas.
 
Since `_computeOfferPrice(total, offerCut)` will not need to be called if an offer is overbid in `.createOffer()`, if an offer expires with `.batchRemoveExpired`, or if an offer is nullified from a frozen contract using `.bidderWithdrawFunds()`, it would be wasteful to call `_computeOfferPrice(total, offerCut)` in `.createOffer()`. 

It only needs to be calculated for offers that end with `.cancelOffer()` or `.fulfillOffer()`, and those are the two places that the calculation is currently done.

**Comment by pengocat** [comment]
Yes, you're right. I misread where the OfferCut parameter is coming from in fulfillOffer(). I stand corrected.
