### ISSUE TITLE
_tryPushFunds does not store which address lost funds for lostAndFound

### ISSUE THREAD

**Issue by michaelKim4736** [dapperlabs/cryptokitties-bounty-2#6]
### Description
_tryPushFunds correctly increments totalLostAndFoundBalance if _to.send fails. However, it does not specify which address failed to receive funds, nor does it maintain a mapping keeping track of how much each address lost. It simply emits an event, but the event is no guarantee that those funds are set aside for only that address. 

### Scenario
_tryPushFunds does not guarantee that _amount send to lostAndFoundFunds will only be withdrawable by the originally intended address 

### Impact
A user who's "_to.send" failed is not contractually guaranteed to receive lostAndFound funds.
The function does emit an event, but maintaining user's LostAndFound balances with an event does not allow the user's balance to be atomically decremented upon withdrawal.

### Reproduction
In OffersBase.sol, if send fails, totalLostAndFoundBalance will be incremented, but only an event is emitted with the address of the recipient. The recipient's address is not stored in this contract or any other contract, so there is no guarantee of funds being returned.

### Fix
Specify a mapping from address to uint256 for lostAndFoundBalance per address.

**Comment by zhangchiqing** [comment]
Hi @michaelKim4736,

Thanks for the feedback. I agree using a mapping would be more clear. However, it will cost more gas to store all these information and make the withdraw more complicated. Since it's very likely to be an edge case, we decided to keep it simple and let the `PushFundsFailed` event being the source of truth for who lost how much. And we will define a process of how to claim the lost fund. 

Closing now. Thanks for the feedback.
