### ISSUE TITLE
Missing typecast of offerCut variable from uint16 to uint256

### ISSUE THREAD

**Issue by michaelKim4736** [dapperlabs/cryptokitties-bounty-2#9]
### Description
In createOffer, uint256_offerCut is assigned the value of offerCut. However, offerCut is a uint16, and should be explicitly typecast to a uint256.

### Scenario
Solidity requires an explicit typecast of a uint16 to a uint256 if assigning.

### Impact
In createOffer, assignment of uint256 _offerCut from uint16 offerCut will fail.

### Reproduction
Observe the following line of code:

uint256 _offerCut = offerCut;

Note that it lacks an explicit typecast on the right side of the equals sign.

### Fix
In Offers.sol createOffer function, change this line of code: 

uint256 _offerCut = offerCut;

to this:

uint256 _offerCut = uint256(offerCut);

**Comment by zhangchiqing** [comment]
Hi michaelKim4736 

Thanks for the feedback. I think you are looking at the wrong offerCut.

The offerCut here is referring to the `uint256 public offerCut` in [OfferCofig.sol](https://github.com/dapperlabs/cryptokitties-bounty-2/blob/master/contracts/OffersConfig.sol#L50), and since it's already `uint256`, it doesn't need explicit typecast. 

The `uint16 offerCut` you mentioned is [a field of the Offer struct](https://github.com/dapperlabs/cryptokitties-bounty-2/blob/master/contracts/OffersBase.sol#L114). 

Closing now. Thanks for the feedback
